### ISSUE TITLE
Need assistance pushing project forward

### ISSUE THREAD

**Issue by doesdev** [musocrat/jsaudio#1]
I've unfortunately failed to progress this library, which in my opinion, could fill a needed gap in the node low-level audio area. There are other libraries, but the biggest issue that I've found with those libraries is how far they are from the PortAudio API (as well as a few other fundamental issues).

Anyway, I've had another baby (#4) and have been neck deep in a project at my day job which has left me with no time to devote to the project. Additionally, and probably more of an issue than time, I have very minimal experience with C++. What time I have spent on this project was 60% learning C++, 35% learning NAN, and 5% writing code.

For those reasons it feels irresponsible for this library to remain under my account without progress. I have moved this repo into an organization @JsAudioOrg and invite contributors to join. I would like to formalize some project goals and such to ensure more than anything we maintain the primary goal of a mostly transparent conversion of the PortAudio API to javascript in the same way that PyAudio has for Python.

**Comment by jacobcpeters** [comment]
I currently have the addon outputting sound. My plan is to get the blocking parts of the API implemented. Then I will start writing some documentation. Finally, I'll look further into implementing a callback. I've already thought of some ideas to overcome the inherent problems entailed.

You can check out the progress in my form. I plan on submitting a pull request soonish.

Thank you for writing the initial code @musocrat. It made getting everything going much easier.

**Comment by doesdev** [comment]
Thanks so much for all your work on this. Feel free to let me know if there is anything specific I can assist with. I'm going to clean up some of the js that I threw in there which was little more than hacky test stuff and start on tests. Let me know if you have a preference on testing framework. For now I'll probably just use mocha for some basic tests. Also, if you've already started on those items let me know and I can hold off. Thanks
