### ISSUE TITLE
Move testing code into the test folder

### ISSUE THREAD

**Issue by jacobcpeters** [musocrat/jsaudio#6]
The tests need to be removed from index.js before discussion can begin on the public API for the addon

**Comment by doesdev** [comment]
I've added some very basics tests using [ava](https://github.com/sindresorhus/ava). Basically just covering the simple functions. I haven't added tests for any of the actual audio functions yet. 

I did clean up the index file and made an example folder which I added the [blocking sine](http://portaudio.com/docs/v19-doxydocs/paex__write__sine_8c_source.html) example to. It should just run after rebuilding, as it calls the default sound device.
